### ISSUE TITLE
Geolocate IPs for downloads

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApi#25]
Look for a **free** API to do basic geolocation for downloads.  We just need a rough city/metro level, not anything precise.  If one can be found then log the lat/long with each download record.  Also log a text description of the location "Tulsa, OK - USA".  The end goal is to hopefully produce a map like this for the admin download reports.

![image](https://user-images.githubusercontent.com/1447203/168836726-f5e95d72-eb81-4422-a10a-680c00aee084.png)

**Comment by PhotoPaul** [comment]
There is a multitude of free options available but they each have their own limits (e.g. https://rapidapi.com/blog/ip-geolocation-api/). Do you have a ballpark figure of the request volume that will be needed?

You should also consider caching responses so that you don't keep sending requests about the same IPs over and over again.

**Comment by jzongker** [comment]
Agreed on caching.  In-memory caching isn't really a viable option with Lambda, but a simple DB query to see if we already have geolocation data for this IP in the downloads table would do the job.

I'd say 1-10k requests per month should cover us for the foreseeable future.

**Comment by jzongker** [comment]
I'm going to handle this one.  Looks like ipgeolocation.io is a good, truly free option.

**Comment by jzongker** [comment]
Added a background process to lookup the IP data.  Still need to display the map on the front-end.
